"""empty message

Revision ID: 2be39de3b27b
Revises: None
Create Date: 2016-04-25 19:27:28.539499

"""

# revision identifiers, used by Alembic.
revision = '2be39de3b27b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderTool',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['OrderTable.OrderID'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['ToolTable.ToolID'], ),
    sa.PrimaryKeyConstraint('order_id', 'tool_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderTool')
    ### end Alembic commands ###
